spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-security
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret:
    key: "689A39E26909FFC12CC9263F4A84A8E9F5855E3935BF1DC9B0243EA960D21EA4"

